[build-system]
requires = ["scikit-build-core>=0.11"]
build-backend = "scikit_build_core.build"

[project]
name = "tracy_client"
dynamic = ["version"]
description = "A real time, nanosecond resolution, remote telemetry, hybrid frame and sampling profiler for games and other applications."
authors = [
  { name = "Bartosz Taudul", email = "wolf@nereid.pl" },
]
requires-python = ">=3.10"

[project.urls]
homepage = "https://github.com/wolfpld/tracy"
source = "https://github.com/wolfpld/tracy"

[tool.scikit-build]
minimum-version = "0.11"
cmake.version = ">=3.15.0"
ninja.version = ">=1.11"
cmake.source-dir = ".."
cmake.build-type = "Release"
wheel.install-dir = "tracy_client"
wheel.packages = ["tracy_client"]

[tool.scikit-build.cmake.define]
TRACY_CLIENT_PYTHON = "ON"
TRACY_STATIC = "OFF"
CMAKE_INSTALL_BINDIR = ""

[tool.scikit-build.metadata.version]
provider = "scikit_build_core.metadata.regex"
input = "../public/common/TracyVersion.hpp"
regex = 'Major = (?P<major>[0-9]+);\s*constexpr int Minor = (?P<minor>[0-9]+);\s*constexpr int Patch = (?P<patch>[0-9]+);'
result = "{major}.{minor}.{patch}"
